# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  gr-latest-x86_64-linux = {
    pname = "gr-latest-x86_64-linux";
    version = "19853152";
    src = fetchurl {
      url = "https://gr-framework.org/downloads/gr-0.64.3-Debian-x86_64.tar.gz";
      sha256 = "sha256-mQhLb0j+U8Dv8S2DG9jNqN1Kmit3zitAk5OvcKpOmq4=";
    };
  };
}
