
[depot.x86_64-linux.fetchzip.artifact-4f01ca82b02afe6cdbe200a8f5c9849eac642482]
name = "artifacts/4f01ca82b02afe6cdbe200a8f5c9849eac642482"
sha256 = "sha256-hTvFbVORfMtTcljGl1LY7kgFXlNE5kO41v0R4IlLhFY="
stripRoot = false
url = "https://pkg.julialang.org/artifact/4f01ca82b02afe6cdbe200a8f5c9849eac642482#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-e63503984ff7722ba80209eddd5621acca0d2d5e]
name = "artifacts/e63503984ff7722ba80209eddd5621acca0d2d5e"
sha256 = "sha256-MACmCYGWNxawil85G6rC7ejD+9+vGXVGrw4van7AvhI="
stripRoot = false
url = "https://pkg.julialang.org/artifact/e63503984ff7722ba80209eddd5621acca0d2d5e#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-f792596249694cc12db3689d386d3a6c5d24e794]
name = "artifacts/f792596249694cc12db3689d386d3a6c5d24e794"
sha256 = "sha256-plKAOVNjEDvf0w2p+6IXrenPrHbd5B7iKOovU+5u+bo="
stripRoot = false
url = "https://pkg.julialang.org/artifact/f792596249694cc12db3689d386d3a6c5d24e794#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-fac7e6d8fc4c5775bf5118ab494120d2a0db4d64]
name = "artifacts/fac7e6d8fc4c5775bf5118ab494120d2a0db4d64"
sha256 = "sha256-wuSLI2PZ4SczLDqodN7CYjI7hswN1ZegUo86Tvnawq4="
stripRoot = false
url = "https://pkg.julialang.org/artifact/fac7e6d8fc4c5775bf5118ab494120d2a0db4d64#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac]
name = "artifacts/dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac"
sha256 = "sha256-27PVVCJaJplznvzgGGwQE3ksOuaUarHOYmDfMKSbUug="
stripRoot = false
url = "https://pkg.julialang.org/artifact/dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.package-OpenSSL]
name = "packages/OpenSSL/kra0W"
sha256 = "sha256-muCjqNy2lqSc78Tzv7q4G9vsYHNcv+olkqf8j1CbGiQ="
stripRoot = false
url = "https://pkg.julialang.org/package/4d8831e6-92b7-49fb-bdf8-b643e874388c/df6830e37943c7aaa10023471ca47fb3065cc3c4#package.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-33c5e3a13ad6427f86436f577c0edce1e468ac80]
name = "artifacts/33c5e3a13ad6427f86436f577c0edce1e468ac80"
sha256 = "sha256-yHv+b8WLS2yJKgp6tbVsvEtiki5DNBKGuXiNaRjo+Oo="
stripRoot = false
url = "https://pkg.julialang.org/artifact/33c5e3a13ad6427f86436f577c0edce1e468ac80#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-NQM4+e9O5BFdeeqsr8OMKnFDdRIy79zOQjPOpdR83es="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/aa3b04713a506a40072b9f0f5f83ab8d80f560bc#registry.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-53037ac9d528ee46c3526799b407ee52b7c224f3]
name = "artifacts/53037ac9d528ee46c3526799b407ee52b7c224f3"
sha256 = "sha256-nwKbETHxBT7fWziDE/6u+ZJvS/ULH7ewT2llzACAtps="
stripRoot = false
url = "https://pkg.julialang.org/artifact/53037ac9d528ee46c3526799b407ee52b7c224f3#artifact.tar.gz"

[depot.x86_64-linux.fetchgit.package-Git]
name = "packages/Git/EnxqL"
sha256 = "sha256-BqIhF5JJjruCf6jsW5YGKG1RG7FxNn3/X3sxYMb79i8="
rev = "d7bffc3fe097e9589145493c08c41297b457e5d0"
url = "https://github.com/JuliaVersionControl/Git.jl.git"

[depot.x86_64-linux.fetchgit.package-Libiconv_jll]
name = "packages/Libiconv_jll/ovuhc"
sha256 = "sha256-iaR18K1DwP9lq99+8O3zPX0YusApOLtpvw4X1tAg+7Y="
rev = "c7cb1f5d892775ba13767a87c7ada0b980ea0a71"
url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-TranscodingStreams]
name = "packages/TranscodingStreams/6lwEF"
sha256 = "sha256-q5hxeKXi3Ea8fAQL0UWGVJAjmHp4KhMXrwFycnIMyTs="
rev = "e4bdc63f5c6d62e80eb1c0043fcc0360d5950ff7"
url = "https://github.com/JuliaIO/TranscodingStreams.jl.git"

[depot.x86_64-linux.fetchgit.package-Preferences]
name = "packages/Preferences/VmJXL"
sha256 = "sha256-xLlPqNWnuXQX03jlVyaDW4X6HEWgCJrv448gDHPQSbk="
rev = "47e5f437cc0e7ef2ce8406ce1e7e24d44915f88d"
url = "https://github.com/JuliaPackaging/Preferences.jl.git"

[depot.x86_64-linux.fetchgit.package-Expat_jll]
name = "packages/Expat_jll/34w3j"
sha256 = "sha256-76MUkP7Yx5UrJpBeauMVJ0TYCdhYJiGyF4xWei2ZBxw="
rev = "bad72f730e9e91c08d9427d5e8db95478a3c323d"
url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-JSON]
name = "packages/JSON/NeJ9k"
sha256 = "sha256-n2oLLNDn7qsRytMKXKUB653A14Yat+GiK9DgrkVBV9A="
rev = "3c837543ddb02250ef42f4738347454f95079d4e"
url = "https://github.com/JuliaIO/JSON.jl.git"

[depot.x86_64-linux.fetchgit.package-Parsers]
name = "packages/Parsers/gi2J3"
sha256 = "sha256-OdydL0kBs0anNG3UFioPiYbElCc/nohJutG/gKFhwUw="
rev = "6466e524967496866901a78fca3f2e9ea445a559"
url = "https://github.com/JuliaData/Parsers.jl.git"

[depot.x86_64-linux.fetchgit.package-MbedTLS]
name = "packages/MbedTLS/lqmet"
sha256 = "sha256-X0cj/771qRxyVLloNLlhtrQkKKcVWlQxmqxSGVMYCII="
rev = "03a9b9718f5682ecb107ac9f7308991db4ce395b"
url = "https://github.com/JuliaLang/MbedTLS.jl.git"

[depot.x86_64-linux.fetchgit.package-Git_jll]
name = "packages/Git_jll/G4IMQ"
sha256 = "sha256-rEjJehQYEKInDVQMWp4GpE//T6wqsOy4L6rRpiWgdqc="
rev = "6e93d42b97978709e9c941fa43d0f01701f0d290"
url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-TextWrap]
name = "packages/TextWrap/DsImh"
sha256 = "sha256-vn0TEXG+NUvX+SDKkdhbV6o0KAampR+wtNUan1yKkNo="
rev = "9250ef9b01b66667380cf3275b3f7488d0e25faf"
url = "https://github.com/carlobaldassi/TextWrap.jl.git"

[depot.x86_64-linux.fetchgit.package-SimpleBufferStream]
name = "packages/SimpleBufferStream/N1BA4"
sha256 = "sha256-oiV4k4jh+sJLWgbHoO0RWnpPVXHIlENIarRfEnBdqhw="
rev = "874e8867b33a00e784c8a7e4b60afe9e037b74e1"
url = "https://github.com/staticfloat/SimpleBufferStream.jl.git"

[depot.x86_64-linux.fetchgit.package-ArgParse]
name = "packages/ArgParse/bylyV"
sha256 = "sha256-qBM1thqt0id4UridMeChGWigvDVP+PuOBpSyIT9YJAs="
rev = "3102bce13da501c9104df33549f511cd25264d7d"
url = "https://github.com/carlobaldassi/ArgParse.jl.git"

[depot.x86_64-linux.fetchgit.package-CodecBase]
name = "packages/CodecBase/JP712"
sha256 = "sha256-WJ4fn9m8zlpOYS9oZSU0fwYxDTJwjujXDcIBL9IJdwo="
rev = "744128fbfc6fe0739085d995b1756f1856964d4c"
url = "https://github.com/JuliaIO/CodecBase.jl.git"

[depot.x86_64-linux.fetchgit.package-BitFlags]
name = "packages/BitFlags/54Sfp"
sha256 = "sha256-uYuIjfusQHD/cgpQD7XANMDcIfQJmoaMc3qdivl18PI="
rev = "43b1a4a8f797c1cddadf60499a8a077d4af2cd2d"
url = "https://github.com/jmert/BitFlags.jl.git"

[depot.x86_64-linux.fetchgit.package-Gettext_jll]
name = "packages/Gettext_jll/5wIPp"
sha256 = "sha256-rvbsJ0HAiGvY/CIWn0bLqEPqsqcf0PlekgaDkzafHD4="
rev = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-JLLWrappers]
name = "packages/JLLWrappers/QpMQW"
sha256 = "sha256-HCas3QrKJJu2CPtTfe6HLCdajP5j84fxqvXmw6BJGHk="
rev = "abc9885a7ca2052a736a600f7fa66209f96506e1"
url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"

[depot.x86_64-linux.fetchgit.package-HTTP]
name = "packages/HTTP/RyUY8"
sha256 = "sha256-KHDwwrEt8A5w+kX9vjuYhZohfWX/HdAdIYjzRZB3HV8="
rev = "2e13c9956c82f5ae8cbdb8335327e63badb8c4ff"
url = "https://github.com/JuliaWeb/HTTP.jl.git"

[depot.x86_64-linux.fetchgit.package-LoggingExtras]
name = "packages/LoggingExtras/5k9PW"
sha256 = "sha256-B1CPEO6Wy2YiKP8DQjuJlnXB27XkQXJwAkhpLvJagFU="
rev = "cedb76b37bc5a6c702ade66be44f831fa23c681e"
url = "https://github.com/JuliaLogging/LoggingExtras.jl.git"

[depot.x86_64-linux.fetchgit.package-SnoopPrecompile]
name = "packages/SnoopPrecompile/UWvXF"
sha256 = "sha256-MP1NnOIjjyqkYLCATEn+E4idIeOMwBA/ONE4my23eQY="
rev = "f604441450a3c0569830946e5b33b78c928e1a85"
url = "https://github.com/timholy/SnoopCompile.jl.git"

[depot.x86_64-linux.fetchgit.package-URIs]
name = "packages/URIs/6ecRe"
sha256 = "sha256-e6SLgl+EtGcbCS5dP3KPnizWTpqirl4IsjaWu35xoOk="
rev = "ac00576f90d8a259f2c9d823e91d1de3fd44d348"
url = "https://github.com/JuliaWeb/URIs.jl.git"

[depot.x86_64-linux.fetchgit.package-CodecZlib]
name = "packages/CodecZlib/ruMLE"
sha256 = "sha256-BL6c/f/6bbbn6e3qBOWwO3+vxwv7G9P/IpNP6u0ApnY="
rev = "ded953804d019afa9a3f98981d99b33e3db7b6da"
url = "https://github.com/JuliaIO/CodecZlib.jl.git"

[depot.x86_64-linux.fetchgit.package-OpenSSL_jll]
name = "packages/OpenSSL_jll/xqxRS"
sha256 = "sha256-tQNODTzNCX8VGYkHB/zRmza6J8x5M+gDGboPbytmTuw="
rev = "f6e9dba33f9f2c44e08a020b0caf6903be540004"
url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-IniFile]
name = "packages/IniFile/LzI2G"
sha256 = "sha256-7uQSdBYwRvH3/4aKXEE6U+AEMQnPmEGgl6sZt+U6vu4="
rev = "f550e6e32074c939295eb5ea6de31849ac2c9625"
url = "https://github.com/JuliaIO/IniFile.jl.git"

[depot.x86_64-linux.fetchgit.package-XML2_jll]
name = "packages/XML2_jll/nyZEZ"
sha256 = "sha256-wSawHsr2QQb8TSTRrkC165MLLZLzWvQinqnkvRxF6Ho="
rev = "93c41695bc1c08c46c5899f4fe06d6ead504bb73"
url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl.git"
