[[commands]]
name = "init-dev"
command = '''
        julia --project=$PRJ_ROOT/"$@" -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();'
'''
help = "run pkgs.instantiate() in project"

[[commands]]
name = "init"
command = '''
        julia --project=$PRJ_ROOT -e '
        using Pkg;
        Pkg.instantiate();'
'''
help = "run pkgs.instantiate() in project :: develop"

[[commands]]
name = "mkdoc"
category = "doc"
command = "nix run .#x86_64-linux.julia2nix.entrypoints.mkdoc $@"
help = "make julia doc"
