# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gr-latest-x86_64-linux = {
    pname = "gr-latest-x86_64-linux";
    version = "19853152";
    src = fetchurl {
      url = "https://gr-framework.org/downloads/gr-0.72.7-Debian-x86_64.tar.gz";
      sha256 = "sha256-/P2Suphh+UzXwyhrWsVGrT9U6HDDDVneIc3gMW3vGHI=";
    };
  };
}
