
[depot.x86_64-linux.fetchzip.package-PrecompileTools]
name = "packages/PrecompileTools/0yi7r"
sha256 = "sha256-+Z+ox1M2e89Zkygih8urpShShaxs/I06amRYy6n7mIg="
stripRoot = false
url = "https://pkg.julialang.org/package/aea7be01-6a6a-4083-8856-8a6e6704d82a/9673d39decc5feece56ef3940e5dafba15ba0f81#package.tar.gz"

[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-l1V9A/H3BJf87wVqZQfdN88Il87fpMhvJd/dihRZD/4="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/73dd18863d40850ae4be15eade8e886d1e0e662f#registry.tar.gz"

[depot.x86_64-linux.fetchgit.package-JuliaFormatter]
name = "packages/JuliaFormatter/HzhVx"
sha256 = "sha256-NeA2OEi6WaKo/UU8FGXxgNqrWfqtmg8ZaDT9KnltLkw="
rev = "60567b51bd9e1e19ae2fd8a54dcd6bc5994727f0"
url = "https://github.com/domluna/JuliaFormatter.jl.git"

[depot.x86_64-linux.fetchgit.package-Preferences]
name = "packages/Preferences/cAMUE"
sha256 = "sha256-C7xRMO5VB4E2dhvcm4JDAd3Vnf+93bQdNkC1aUr9hDc="
rev = "7eb1686b4f04b82f96ed7a4ea5890a4f0c7a09f1"
url = "https://github.com/JuliaPackaging/Preferences.jl.git"

[depot.x86_64-linux.fetchgit.package-JSON]
name = "packages/JSON/93Ea8"
sha256 = "sha256-vl9/+PMSFTk3K/tQzVWxE2n+FAe4DlYcnpUUs4XMGRY="
rev = "31e996f0a15c7b280ba9f76636b3ff9e2ae58c9a"
url = "https://github.com/JuliaIO/JSON.jl.git"

[depot.x86_64-linux.fetchgit.package-Parsers]
name = "packages/Parsers/47wo2"
sha256 = "sha256-NiitqTraFRL0xYS4QqEYOtyVbK949KuNkRk4VupNvh4="
rev = "b32107a634205cdcc64e2a3070c3eb0d56d54181"
url = "https://github.com/JuliaData/Parsers.jl.git"

[depot.x86_64-linux.fetchgit.package-Glob]
name = "packages/Glob/RCNHV"
sha256 = "sha256-XQJ5aeXm0xFHYlIzpU43qyx4g7laeAj0iu4OP9Q61xc="
rev = "97285bbd5230dd766e9ef6749b80fc617126d496"
url = "https://github.com/vtjnash/Glob.jl.git"

[depot.x86_64-linux.fetchgit.package-TextWrap]
name = "packages/TextWrap/DsImh"
sha256 = "sha256-vn0TEXG+NUvX+SDKkdhbV6o0KAampR+wtNUan1yKkNo="
rev = "9250ef9b01b66667380cf3275b3f7488d0e25faf"
url = "https://github.com/carlobaldassi/TextWrap.jl.git"

[depot.x86_64-linux.fetchgit.package-CSTParser]
name = "packages/CSTParser/VcYj6"
sha256 = "sha256-8wxZ/b90hDZFQZTmdC+WhKFgI1WnuB7hoGRj8c1WfvA="
rev = "3ddd48d200eb8ddf9cb3e0189fc059fd49b97c1f"
url = "https://github.com/julia-vscode/CSTParser.jl.git"

[depot.x86_64-linux.fetchgit.package-Compat]
name = "packages/Compat/sZEKP"
sha256 = "sha256-GEEM5mlpvIdVUpMFJf53WSFpv1r6lp78WATf0PFyUNs="
rev = "7a60c856b9fa189eb34f5f8a6f6b5529b7942957"
url = "https://github.com/JuliaLang/Compat.jl.git"

[depot.x86_64-linux.fetchgit.package-ArgParse]
name = "packages/ArgParse/bylyV"
sha256 = "sha256-qBM1thqt0id4UridMeChGWigvDVP+PuOBpSyIT9YJAs="
rev = "3102bce13da501c9104df33549f511cd25264d7d"
url = "https://github.com/carlobaldassi/ArgParse.jl.git"

[depot.x86_64-linux.fetchgit.package-Tokenize]
name = "packages/Tokenize/d4Pxs"
sha256 = "sha256-UcY7hZ03SaftHZ8mRgiaU8NVEvM8AEv3g7Ui66JS3YU="
rev = "90538bf898832b6ebd900fa40f223e695970e3a5"
url = "https://github.com/JuliaLang/Tokenize.jl.git"

[depot.x86_64-linux.fetchgit.package-OrderedCollections]
name = "packages/OrderedCollections/vTcqn"
sha256 = "sha256-/+7Zbpf3FwRUPb5/4/HQVafTOcb85u+w6hihedt4G18="
rev = "d321bf2de576bf25ec4d3e4360faca399afca282"
url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"

[depot.x86_64-linux.fetchgit.package-Crayons]
name = "packages/Crayons/u3AH8"
sha256 = "sha256-7fZ3X+fB9nBf+Ly45nlRb5ZEFEoZ5kPZXZRTdgVYy20="
rev = "249fe38abf76d48563e2f4556bebd215aa317e15"
url = "https://github.com/KristofferC/Crayons.jl.git"

[depot.x86_64-linux.fetchgit.package-CommonMark]
name = "packages/CommonMark/eJY7b"
sha256 = "sha256-em8nj/OYwrnuF5Nko2x3pldWK4YSpMUOlEhIgwNrkLI="
rev = "532c4185d3c9037c0237546d817858b23cf9e071"
url = "https://github.com/MichaelHatherly/CommonMark.jl.git"

[depot.x86_64-linux.fetchgit.package-URIs]
name = "packages/URIs/gpp9J"
sha256 = "sha256-PBHbjYBXEXVB0OKWuYZrsuoTa3tGo+tqkGaLKdLS27Y="
rev = "074f993b0ca030848b897beff716d93aca60f06a"
url = "https://github.com/JuliaWeb/URIs.jl.git"

[depot.x86_64-linux.fetchgit.package-DataStructures]
name = "packages/DataStructures/59MD0"
sha256 = "sha256-D7O8UamRre+kEtHvnqDMnJwdsmXfn5OzBSil0Qh7ecY="
rev = "d1fff3a548102f48987a52a2e0d114fa97d730f0"
url = "https://github.com/JuliaCollections/DataStructures.jl.git"
