
[depot.x86_64-linux.fetchzip.package-JuliaFormatter]
name = "packages/JuliaFormatter/vo3e0"
sha256 = "sha256-R1VVfBRSD/nRvDB5cZLdGVm0yD4MVHT3bWwdIsc8/s8="
stripRoot = false
url = "https://pkg.julialang.org/package/98e50ef6-434e-11e9-1051-2b60c6c9e899/6c0fd08be0dc54f11c224374ad6da743ce6a8ca0#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-JSON]
name = "packages/JSON/NeJ9k"
sha256 = "sha256-n2oLLNDn7qsRytMKXKUB653A14Yat+GiK9DgrkVBV9A="
stripRoot = false
url = "https://pkg.julialang.org/package/682c06a0-de6a-54ab-a142-c8b1cf79cde6/3c837543ddb02250ef42f4738347454f95079d4e#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Parsers]
name = "packages/Parsers/KmPKe"
sha256 = "sha256-Dj8wZ/WCma54o0rC7aZ2eZydKhkX1diWzSnFN9wThIY="
stripRoot = false
url = "https://pkg.julialang.org/package/69de0a69-1ddd-5017-9359-2bf0b02dc9f0/0044b23da09b5608b4ecacb4e5e6c6332f833a7e#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-TextWrap]
name = "packages/TextWrap/DsImh"
sha256 = "sha256-vn0TEXG+NUvX+SDKkdhbV6o0KAampR+wtNUan1yKkNo="
stripRoot = false
url = "https://pkg.julialang.org/package/b718987f-49a8-5099-9789-dcd902bef87d/9250ef9b01b66667380cf3275b3f7488d0e25faf#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-CSTParser]
name = "packages/CSTParser/VcYj6"
sha256 = "sha256-8wxZ/b90hDZFQZTmdC+WhKFgI1WnuB7hoGRj8c1WfvA="
stripRoot = false
url = "https://pkg.julialang.org/package/00ebfdb7-1f24-5e51-bd34-a7502290713f/3ddd48d200eb8ddf9cb3e0189fc059fd49b97c1f#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Compat]
name = "packages/Compat/x4NFm"
sha256 = "sha256-SNJ2yasrxtmC/hSUxkubEJMn3oa9HR5Qjri3cwgm/XU="
stripRoot = false
url = "https://pkg.julialang.org/package/34da2185-b29b-5c13-b0c7-acf172513d20/924cdca592bc16f14d2f7006754a621735280b74#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-ArgParse]
name = "packages/ArgParse/bylyV"
sha256 = "sha256-qBM1thqt0id4UridMeChGWigvDVP+PuOBpSyIT9YJAs="
stripRoot = false
url = "https://pkg.julialang.org/package/c7e460c6-2fb9-53a9-8c5b-16f535851c63/3102bce13da501c9104df33549f511cd25264d7d#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Tokenize]
name = "packages/Tokenize/bZ0tu"
sha256 = "sha256-cVxgoO4ACSUDPHX7g9Xr7I12P7SOGuH/VnGDpqzxbdA="
stripRoot = false
url = "https://pkg.julialang.org/package/0796e94c-ce3b-5d07-9a54-7f471281c624/2b3af135d85d7e70b863540160208fa612e736b9#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-OrderedCollections]
name = "packages/OrderedCollections/PRayh"
sha256 = "sha256-jkM6lAXu8+UnsrzYeCI4GqT/YpvRBxB+xvejO3dlXUk="
stripRoot = false
url = "https://pkg.julialang.org/package/bac558e1-5e72-5ebc-8fee-abe8a469f55d/85f8e6578bf1f9ee0d11e7bb1b1456435479d47c#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Crayons]
name = "packages/Crayons/u3AH8"
sha256 = "sha256-7fZ3X+fB9nBf+Ly45nlRb5ZEFEoZ5kPZXZRTdgVYy20="
stripRoot = false
url = "https://pkg.julialang.org/package/a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f/249fe38abf76d48563e2f4556bebd215aa317e15#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-CommonMark]
name = "packages/CommonMark/qXeHg"
sha256 = "sha256-lWXwM+BaPWCQ7woHwyhV2bmV56F0FnKgfIQbUKw6ejI="
stripRoot = false
url = "https://pkg.julialang.org/package/a80b9123-70ca-4bc0-993e-6e3bcb318db6/4cd7063c9bdebdbd55ede1af70f3c2f48fab4215#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-URIs]
name = "packages/URIs/JmxRD"
sha256 = "sha256-yW+GHRfEnzbVD2OjxrjIUutx6cBNhqVT8S/v9jaP6MI="
stripRoot = false
url = "https://pkg.julialang.org/package/5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4/e59ecc5a41b000fa94423a578d29290c7266fc10#package.tar.gz"

[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-0bp6X1P4qWgEXkskOIYnKmNQ739LuTD+o8+rvabQid8="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/b37df9cfe3612d53defba7a527408b0a75401453#registry.tar.gz"

[depot.x86_64-linux.fetchzip.package-DataStructures]
name = "packages/DataStructures/59MD0"
sha256 = "sha256-D7O8UamRre+kEtHvnqDMnJwdsmXfn5OzBSil0Qh7ecY="
stripRoot = false
url = "https://pkg.julialang.org/package/864edb3b-99cc-5e75-8d2d-829cb0a9cfe8/d1fff3a548102f48987a52a2e0d114fa97d730f0#package.tar.gz"
