# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  julia-17-aarch64-darwin = {
    pname = "julia-17-aarch64-darwin";
    version = "1.7.2-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/aarch64/1.7/julia-1.7.2-macaarch64.dmg";
      sha256 = "sha256-Qg2OODnD45QH9TZc6zv7hImaRAkV7IljkFaAFbP/pLk=";
    };
  };
  julia-17-aarch64-linux = {
    pname = "julia-17-aarch64-linux";
    version = "1.7.2-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/aarch64/1.7/julia-1.7.3-linux-aarch64.tar.gz";
      sha256 = "sha256-2eizQsgK0TcVIO1tEfVbeKpgdGc3+/V+yv1qI7Ut1x0=";
    };
  };
  julia-17-x86_64-darwin = {
    pname = "julia-17-x86_64-darwin";
    version = "1.7.3-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.7/julia-1.7.3-mac64.dmg";
      sha256 = "sha256-Z3mewGz1e8qAqKHG5aFwSF07/ARhshdpmwcw2jfQZW8=";
    };
  };
  julia-17-x86_64-linux = {
    pname = "julia-17-x86_64-linux";
    version = "1.7.3-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz";
      sha256 = "sha256-my9PoS2StNzF0R3Gb7EYxHaBp209+NoGTMl1c/L1xzk=";
    };
  };
  julia-19-aarch64-darwin = {
    pname = "julia-19-aarch64-darwin";
    version = "1.9.3-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/aarch64/1.9/julia-1.9.3-macaarch64.dmg";
      sha256 = "sha256-zKczQExJufOc1niNrvV8S3oNciLUKx018A69bk/AP30=";
    };
  };
  julia-19-aarch64-linux = {
    pname = "julia-19-aarch64-linux";
    version = "1.9.3-linux-aarch64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/aarch64/1.9/julia-1.9.3-linux-aarch64.tar.gz";
      sha256 = "sha256-VUN4efa5hHDZbEBIuSJQG2Q9//uIZavrkMczOoPfdSQ=";
    };
  };
  julia-19-x86_64-darwin = {
    pname = "julia-19-x86_64-darwin";
    version = "1.9.3-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.9/julia-1.9.3-mac64.dmg";
      sha256 = "sha256-qceM0Bl4vWDoONWFWB5YdQMTVZw4CaoK585VLCza/jk=";
    };
  };
  julia-19-x86_64-linux = {
    pname = "julia-19-x86_64-linux";
    version = "1.9.3-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz";
      sha256 = "sha256-12ZwzJuj4P1MFUXdPQAmnAaUl2oRdjEnlevOFpLTI9E=";
    };
  };
  julia-nightly-110-aarch64-darwin = {
    pname = "julia-nightly-110-aarch64-darwin";
    version = "be2c35a8d2";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/macos/aarch64/1.10/julia-be2c35a8d2-macos-aarch64.dmg";
      sha256 = "sha256-f4WWN/2vDa4hqRcCqQ7lWFzGFdE1dkBpgtmdyJS+Otc=";
    };
  };
  julia-nightly-110-aarch64-linux = {
    pname = "julia-nightly-110-aarch64-linux";
    version = "be2c35a8d2";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/linux/aarch64/1.10/julia-be2c35a8d2-linux-aarch64.tar.gz";
      sha256 = "sha256-Zgq6No/jKocvFakcK7r6QlE2ARIYMZonTGVBzZageKo=";
    };
  };
  julia-nightly-110-x86_64-darwin = {
    pname = "julia-nightly-110-x86_64-darwin";
    version = "be2c35a8d2";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/macos/x86_64/1.10/julia-be2c35a8d2-macos-x86_64.dmg";
      sha256 = "sha256-UUbizludvliGV+msTxReqQqYtxf91YZKStB/e8/eB/o=";
    };
  };
  julia-nightly-110-x86_64-linux = {
    pname = "julia-nightly-110-x86_64-linux";
    version = "be2c35a8d2";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/1.10/julia-be2c35a8d2-linux-x86_64.tar.gz";
      sha256 = "sha256-ld0hLM0oSfU+wXSm6dLbQcnBPKjeNbkNSbP04DxIYpY=";
    };
  };
}
