# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  julia-17-release-mac64 = {
    pname = "julia-17-release-mac64";
    version = "1.7.2-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.7/julia-1.7.2-mac64.dmg";
      sha256 = "sha256-rp0pcO2Jh7nEjxZrFfAtva4Bf0jhBlIlQK3ZAw8Qbw4=";
    };
  };
  julia-17-release-macaarch64 = {
    pname = "julia-17-release-macaarch64";
    version = "1.7.2-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/aarch64/1.7/julia-1.7.2-macaarch64.dmg";
      sha256 = "sha256-Qg2OODnD45QH9TZc6zv7hImaRAkV7IljkFaAFbP/pLk=";
    };
  };
  julia-18-beta-aarch64-linux = {
    pname = "julia-18-beta-aarch64-linux";
    version = "1.8.0-beta3-linux-aarch64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/aarch64/1.8/julia-1.8.0-beta3-linux-aarch64.tar.gz";
      sha256 = "sha256-Q9I/EUoqghfzAHK7mGE+1FqZMBBtvnQVd5Y1cfGGr8c=";
    };
  };
  julia-18-beta-mac64 = {
    pname = "julia-18-beta-mac64";
    version = "1.8.0-beta3-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.8/julia-1.8.0-beta3-mac64.dmg";
      sha256 = "sha256-+IC1597HvrlxUJI4MF003rpXfQZdqhWEXuNNnIBRly8=";
    };
  };
  julia-18-beta-macaarch64 = {
    pname = "julia-18-beta-macaarch64";
    version = "1.8.0-beta3-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/aarch64/1.8/julia-1.8.0-beta3-macaarch64.dmg";
      sha256 = "sha256-ZxFOvZyDXpPXj9MMou0HeCEV7v09tCYERyBUeoi+9Wg=";
    };
  };
  julia-18-beta-x86_64-linux = {
    pname = "julia-18-beta-x86_64-linux";
    version = "1.8.0-beta3-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.0-beta3-linux-x86_64.tar.gz";
      sha256 = "sha256-dJsvPGgyp7NEBIOOV53pTDaRcyUMBwcTg8tJnxSBJlU=";
    };
  };
}
