
[depot.x86_64-linux.fetchzip.package-TranscodingStreams]
name = "packages/TranscodingStreams/DYpJd"
sha256 = "sha256-hdHVTW2azsr2/zNV0B2XX5pdsQSD7YKOUa1tBm3R3i0="
stripRoot = false
url = "https://pkg.julialang.org/package/3bb67fe8-82b1-5028-8e26-92a6c54297fa/8a75929dcd3c38611db2f8d08546decb514fcadf#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-DocumenterLaTeX]
name = "packages/DocumenterLaTeX/rVYaT"
sha256 = "sha256-ZOtJBAt1ezn6GVlhBPYBRc948mecgKKOa1+7AF68a9g="
stripRoot = false
url = "https://pkg.julialang.org/package/cd674d7a-5f81-5cf3-af33-235ef1834b99/653299370be20ff580bccd707dc9f360c0852d7f#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-JSON]
name = "packages/JSON/NeJ9k"
sha256 = "sha256-n2oLLNDn7qsRytMKXKUB653A14Yat+GiK9DgrkVBV9A="
stripRoot = false
url = "https://pkg.julialang.org/package/682c06a0-de6a-54ab-a142-c8b1cf79cde6/3c837543ddb02250ef42f4738347454f95079d4e#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Documenter]
name = "packages/Documenter/6vUwN"
sha256 = "sha256-SUcTJM6Kx8XVBYikfRFQQAtBvvkPatUgK4AX0WfuU8s="
stripRoot = false
url = "https://pkg.julialang.org/package/e30172f5-a6a5-5a46-863b-614d45cd2de4/a4875e0763112d6d017126f3944f4133abb342ae#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-Parsers]
name = "packages/Parsers/34hDN"
sha256 = "sha256-m7AlGdiKQoUSdgUOAsZ6FUFQLAUotX1wYhtTTRHGL7k="
stripRoot = false
url = "https://pkg.julialang.org/package/69de0a69-1ddd-5017-9359-2bf0b02dc9f0/3d5bf43e3e8b412656404ed9466f1dcbf7c50269#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-MbedTLS]
name = "packages/MbedTLS/yELM7"
sha256 = "sha256-W6G0C7HDds740mu8roRMAAGRPxtf5M2vb4Zgep84ABU="
stripRoot = false
url = "https://pkg.julialang.org/package/739be429-bea8-5141-9913-cc70e7f3736d/6872f9594ff273da6d13c7c1a1545d5a8c7d0c1c#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-SimpleBufferStream]
name = "packages/SimpleBufferStream/N1BA4"
sha256 = "sha256-oiV4k4jh+sJLWgbHoO0RWnpPVXHIlENIarRfEnBdqhw="
stripRoot = false
url = "https://pkg.julialang.org/package/777ac1f9-54b0-4bf8-805c-2214025038e7/874e8867b33a00e784c8a7e4b60afe9e037b74e1#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-LiveServer]
name = "packages/LiveServer/WnWLK"
sha256 = "sha256-fnqIn3v6g7EEOhPi8BDmWwgFK6zsfDxwYG9eFD4GQE8="
stripRoot = false
url = "https://pkg.julialang.org/package/16fef848-5104-11e9-1b77-fb7a48bbb589/3251b35f4f9a18d9c83a5d4d63bda5110537cf9c#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-DocStringExtensions]
name = "packages/DocStringExtensions/iscC8"
sha256 = "sha256-hwdg0qDEb0q2sR02MADJzQgXpQtiLMTqqjA7r/QGJ3Q="
stripRoot = false
url = "https://pkg.julialang.org/package/ffbed154-4ef7-542d-bbb7-c09d3a79fcae/b19534d1895d702889b219c382a6e18010797f0b#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-HTTP]
name = "packages/HTTP/PesRN"
sha256 = "sha256-LjfKMrHdk2UtCAA+Bcn0B7SMhu3kNDYOZu2ADm3T2QY="
stripRoot = false
url = "https://pkg.julialang.org/package/cd3eb016-35fb-5094-929b-558a96fad6f3/59ba44e0aa49b87a8c7a8920ec76f8afe87ed502#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-IOCapture]
name = "packages/IOCapture/wJ3yD"
sha256 = "sha256-sIgkhjyQHvVDrxrgTEBAIwxT0X/74gGJAYbMWp66qHI="
stripRoot = false
url = "https://pkg.julialang.org/package/b5f81e59-6552-4d32-b1f0-c071b021bf89/377252859f740c217b936cebcd918a44f9b53b59#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-LoggingExtras]
name = "packages/LoggingExtras/zT9ZU"
sha256 = "sha256-dh6B2gKpHH+26SMCK56yRq9GC6HDs7fCW8ILwgj8l/Q="
stripRoot = false
url = "https://pkg.julialang.org/package/e6f89c97-d47a-5376-807f-9c37f3926c36/5d4d2d9904227b8bd66386c1138cf4d5ffa826bf#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-URIs]
name = "packages/URIs/JmxRD"
sha256 = "sha256-yW+GHRfEnzbVD2OjxrjIUutx6cBNhqVT8S/v9jaP6MI="
stripRoot = false
url = "https://pkg.julialang.org/package/5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4/e59ecc5a41b000fa94423a578d29290c7266fc10#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-CodecZlib]
name = "packages/CodecZlib/ruMLE"
sha256 = "sha256-BL6c/f/6bbbn6e3qBOWwO3+vxwv7G9P/IpNP6u0ApnY="
stripRoot = false
url = "https://pkg.julialang.org/package/944b1d66-785c-5afd-91f1-9de20f533193/ded953804d019afa9a3f98981d99b33e3db7b6da#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-IniFile]
name = "packages/IniFile/LzI2G"
sha256 = "sha256-7uQSdBYwRvH3/4aKXEE6U+AEMQnPmEGgl6sZt+U6vu4="
stripRoot = false
url = "https://pkg.julialang.org/package/83e8ac13-25f8-5344-8a64-a9f2b223428f/f550e6e32074c939295eb5ea6de31849ac2c9625#package.tar.gz"

[depot.x86_64-linux.fetchzip.package-MIMEs]
name = "packages/MIMEs/nC91A"
sha256 = "sha256-UyqZr10VLNnCLM+rsKhsKdGkXtZ4sdOvCTWvVwUW7G0="
stripRoot = false
url = "https://pkg.julialang.org/package/6c6e2e6c-3030-632d-7369-2d6c69616d65/65f28ad4b594aebe22157d6fac869786a255b7eb#package.tar.gz"

[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-zxMhuvTHx1ICD5p3s9pwvqCmtfPHB4xPTnbKAQtXZJU="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/2c7aace86f615932f40f3968e81796a3ff6ecaef#registry.tar.gz"
