name: "nightly-update"
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * SUN" # every sunday

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Julia Version Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          nix develop .#update --command nvfetcher-update

      - name: "Create Pull Request"
        uses: "peter-evans/create-pull-request@v5"
        with:
          branch: "auto_update_nightly"
          title: "Update nightly versions"
          body: |
            Automatically updated the nightly version
