name: "nightly-update"
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * SUN" # every sunday

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Julia Version Update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        nix develop .#update --command nvfetcher-update

    - name: Commit changes
      if: ${{ env.COMMIT_MSG != null }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.COMMIT_MSG }}
