name: "nix-linux"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v18
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20221202_b4b1338/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    - uses: cachix/cachix-action@v12
      with:
        name: zeek

    - name: Nix Flake Show
      run: nix flake show

    - name: Check Julia Version
      run: nix develop --show-trace --command -- julia --version

    - name: Build julia2nix with nix develop
      run: nix develop --show-trace --command -- init

    - name: Build JuliaDoc
      run: nix run -Lv .#x86_64-linux.julia2nix.entrypoints.mkdoc docs

    - name: Check Template Shells
      run: |
        nix develop ./templates/dev --show-trace --override-input julia2nix ./. --command -- julia --version

    - name: Check julia2nix tests
      run: |
        nix develop --show-trace --command -- mktest

    - name: Build Julia Wrapped
      run: |
        nix run .#packages.x86_64-linux.julia-wrapped --print-build-logs -- --version

    - name: Build Depot Path
      run: |
        nix build .#packages.x86_64-linux.build-depot --print-build-logs

    - name: Build Julia2Project and write julia2nix.toml
      run: |
        nix -Lv develop --command buildProject

    - name: Build jlrs -> call_julia
      run: |
        nix develop ./templates/jlrs --override-input julia2nix ./. --show-trace --command -- call-julia

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      if: ${{ github.event_name == 'push' }}
      with:
        branch: gh-pages
        folder: ./docs/build
