name: nix-macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Init julia2nix.jl with nix develop
      run: |
        nix develop --show-trace --command -- init

    # - name: Check julia2nix tests
    #   run: |
    #     nix develop --show-trace --command -- mktest

    - name: Write julia2nix.toml
      run: |
        nix develop --show-trace --command -- writejulia2nix

    - name: Build Julia2nix Project
      run: |
        nix build .#packages.x86_64-darwin.build-project --print-build-logs
