name: "nix-linux"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - uses: cachix/install-nix-action@v17
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.9.0pre20220428_660835d/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix


    # - name: Nix Flake Check
    #   run: nix -Lv flake check
    - name: Nix Flake Show
      run: nix flake show

    - name: Check Julia Version
      run: nix develop --show-trace --command -- julia --version

    - name: Build julia2nix with nix develop
      run: nix develop --show-trace --command -- init

    - name: Check Template Shells
      run: |
        nix develop ./templates/dev --show-trace --override-input julia2nix ./. --command -- julia --version

    - name: Check julia2nix tests
      run: |
        nix develop --show-trace --command -- mktest

    - name: Build Julia Wrapped
      run: |
        nix run .#packages.x86_64-linux.julia-wrapped --print-build-logs -- --version

    - name: Build Depot Path
      run: |
        nix build .#packages.x86_64-linux.test-depot --print-build-logs

    - name: Build Julia2Project and write Depot.nix
      run: |
        nix develop -c nix run .#packages.x86_64-linux.build-project --print-build-logs -- testenv/writeDepot.jl

    - name: Build jlrs -> call_julia
      run: |
        nix develop --show-trace --command -- jlrs-call-julia

    - name: Build Doc
      run: |
        nix develop --show-trace --command -- init-dev docs
        nix develop --show-trace --command -- mkdoc-jl
        nix develop --show-trace --command -- mkdoc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: ./docs/publish/public
