name: "Nix"
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - uses: cachix/install-nix-action@v17
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.9.0pre20220428_660835d/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix


    - name: Nix Flake Check
      run: nix -Lv flake check

    - name: Check Julia Version
      run: nix -Lv develop -c julia --version

    - name: Build julia2nix with nix develop
      run: nix -Lv develop -c julia --version

    - name: Build Doc
      run: |
        nix -Lv develop -c mkdoc-init
        nix -Lv develop -c mkdoc
