
[depot.x86_64-linux.fetchzip.artifact-2e8fae88dcadc37883e31246fe7397f4f1039f88]
name = "artifacts/2e8fae88dcadc37883e31246fe7397f4f1039f88"
sha256 = "sha256-lRAr3t81krlKh9H+nX0+3l0lLS8ndwth6DiZl//MDdU="
stripRoot = false
url = "https://pkg.julialang.org/artifact/2e8fae88dcadc37883e31246fe7397f4f1039f88#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-4f01ca82b02afe6cdbe200a8f5c9849eac642482]
name = "artifacts/4f01ca82b02afe6cdbe200a8f5c9849eac642482"
sha256 = "sha256-hTvFbVORfMtTcljGl1LY7kgFXlNE5kO41v0R4IlLhFY="
stripRoot = false
url = "https://pkg.julialang.org/artifact/4f01ca82b02afe6cdbe200a8f5c9849eac642482#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-fac7e6d8fc4c5775bf5118ab494120d2a0db4d64]
name = "artifacts/fac7e6d8fc4c5775bf5118ab494120d2a0db4d64"
sha256 = "sha256-wuSLI2PZ4SczLDqodN7CYjI7hswN1ZegUo86Tvnawq4="
stripRoot = false
url = "https://pkg.julialang.org/artifact/fac7e6d8fc4c5775bf5118ab494120d2a0db4d64#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac]
name = "artifacts/dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac"
sha256 = "sha256-27PVVCJaJplznvzgGGwQE3ksOuaUarHOYmDfMKSbUug="
stripRoot = false
url = "https://pkg.julialang.org/artifact/dc526f26fb179a3f68eb13fcbe5d2d2a5aa7eeac#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.registry-General]
name = "registries/General"
sha256 = "sha256-N6h7bLr3x6/L9uUM1QAPu5O3JsvtRdf0sAOEfbHi6dg="
stripRoot = false
url = "https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/9f5e00458827b43082c0c83d10259ab043d77ca6#registry.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-33c5e3a13ad6427f86436f577c0edce1e468ac80]
name = "artifacts/33c5e3a13ad6427f86436f577c0edce1e468ac80"
sha256 = "sha256-yHv+b8WLS2yJKgp6tbVsvEtiki5DNBKGuXiNaRjo+Oo="
stripRoot = false
url = "https://pkg.julialang.org/artifact/33c5e3a13ad6427f86436f577c0edce1e468ac80#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-3e19866657986912870f596aecfee137473965a9]
name = "artifacts/3e19866657986912870f596aecfee137473965a9"
sha256 = "sha256-37tlKNldQLoYifcL1OGIa4WMQgoAZpHblEOXh8MniJM="
stripRoot = false
url = "https://pkg.julialang.org/artifact/3e19866657986912870f596aecfee137473965a9#artifact.tar.gz"

[depot.x86_64-linux.fetchzip.artifact-25fa81dbac6496585a91dbdc258273d39442466f]
name = "artifacts/25fa81dbac6496585a91dbdc258273d39442466f"
sha256 = "sha256-C+jXI3NPFkz3mRtxTm0CWKk4U/GukzkPBF+BH8HC89E="
stripRoot = false
url = "https://pkg.julialang.org/artifact/25fa81dbac6496585a91dbdc258273d39442466f#artifact.tar.gz"

[depot.x86_64-linux.fetchgit.package-Preferences]
name = "packages/Preferences/VmJXL"
sha256 = "sha256-xLlPqNWnuXQX03jlVyaDW4X6HEWgCJrv448gDHPQSbk="
rev = "47e5f437cc0e7ef2ce8406ce1e7e24d44915f88d"
url = "https://github.com/JuliaPackaging/Preferences.jl.git"

[depot.x86_64-linux.fetchgit.package-Parsers]
name = "packages/Parsers/aQvnF"
sha256 = "sha256-eUcwU4USZH4sG2L0AgYpboqRHaPTz2HK/Vpw3+VpPcg="
rev = "6c01a9b494f6d2a9fc180a08b182fcb06f0958a0"
url = "https://github.com/JuliaData/Parsers.jl.git"

[depot.x86_64-linux.fetchgit.package-SodiumSeal]
name = "packages/SodiumSeal/B4QGa"
sha256 = "sha256-mxvaXiIj55/X57fE5B7b7/qsuh15SU6DfPnGwnCZ/GE="
rev = "80cef67d2953e33935b41c6ab0a178b9987b1c99"
url = "https://github.com/christopher-dG/SodiumSeal.jl.git"

[depot.x86_64-linux.fetchgit.package-Tables]
name = "packages/Tables/T7rHm"
sha256 = "sha256-ZpQ3m7gJNykqdbJ4XbRSP3uCfTCQ1joddhNuaWFphP4="
rev = "c79322d36826aa2f4fd8ecfa96ddb47b174ac78d"
url = "https://github.com/JuliaData/Tables.jl.git"

[depot.x86_64-linux.fetchgit.package-BitFlags]
name = "packages/BitFlags/NtHwL"
sha256 = "sha256-wzxxxsnThZO4gCmTg/uwvnpRDpH3jyDqLogVRe8kSUo="
rev = "84259bb6172806304b9101094a7cc4bc6f56dbc6"
url = "https://github.com/jmert/BitFlags.jl.git"

[depot.x86_64-linux.fetchgit.package-OrderedCollections]
name = "packages/OrderedCollections/PRayh"
sha256 = "sha256-jkM6lAXu8+UnsrzYeCI4GqT/YpvRBxB+xvejO3dlXUk="
rev = "85f8e6578bf1f9ee0d11e7bb1b1456435479d47c"
url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"

[depot.x86_64-linux.fetchgit.package-RelocatableFolders]
name = "packages/RelocatableFolders/xuLyx"
sha256 = "sha256-E3fVbrOdCYpVkur0qvpUgfM9hHKCHdQ0S+OVTDL0KnE="
rev = "90bc7a7c96410424509e4263e277e43250c05691"
url = "https://github.com/JuliaPackaging/RelocatableFolders.jl.git"

[depot.x86_64-linux.fetchgit.package-Crayons]
name = "packages/Crayons/u3AH8"
sha256 = "sha256-7fZ3X+fB9nBf+Ly45nlRb5ZEFEoZ5kPZXZRTdgVYy20="
rev = "249fe38abf76d48563e2f4556bebd215aa317e15"
url = "https://github.com/KristofferC/Crayons.jl.git"

[depot.x86_64-linux.fetchgit.package-URIs]
name = "packages/URIs/JmxRD"
sha256 = "sha256-yW+GHRfEnzbVD2OjxrjIUutx6cBNhqVT8S/v9jaP6MI="
rev = "e59ecc5a41b000fa94423a578d29290c7266fc10"
url = "https://github.com/JuliaWeb/URIs.jl.git"

[depot.x86_64-linux.fetchgit.package-Mustache]
name = "packages/Mustache/X2gWh"
sha256 = "sha256-LHye3oVFQTkfWZxMpQ2MCkZHW194aiTGHzbE9W4Pc2w="
rev = "1e566ae913a57d0062ff1af54d2697b9344b99cd"
url = "https://github.com/jverzani/Mustache.jl.git"

[depot.x86_64-linux.fetchgit.package-DataAPI]
name = "packages/DataAPI/3E1DE"
sha256 = "sha256-XrGj9VOJJn6vpx7mTLaivdiojN6SavSF8vZecBmW+HU="
rev = "46d2680e618f8abd007bce0c3026cb0c4a8f2032"
url = "https://github.com/JuliaData/DataAPI.jl.git"

[depot.x86_64-linux.fetchgit.package-OpenSSL_jll]
name = "packages/OpenSSL_jll/FyLfZ"
sha256 = "sha256-qrsDPBjz/nlQZ1k++u9HYiWeowFaWNmT6WjP3qvB2n4="
rev = "e60321e3f2616584ff98f0a4f18d98ae6f89bbb3"
url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-XML2_jll]
name = "packages/XML2_jll/Zf4Jm"
sha256 = "sha256-iS/con9/4+UO/oBmIM0PX7qnfEPCKn60MkX8J3PVaPY="
rev = "58443b63fb7e465a8a7210828c91c08b92132dff"
url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-GarishPrint]
name = "packages/GarishPrint/214Ip"
sha256 = "sha256-E0Yr5wRJwcG+M7cUDBqOoGbcT9ZWoOchl04+2JTPrww="
rev = "41136d24cc02c4d7c2b8c8982823fedac66d0a45"
url = "https://github.com/Roger-luo/GarishPrint.jl.git"

[depot.x86_64-linux.fetchgit.package-OpenSSL]
name = "packages/OpenSSL/pMpWB"
sha256 = "sha256-6ntIYYY4a3bRoAdpnjKIhmmcxKDcq6GCuswS5EkaYyY="
rev = "3c3c4a401d267b04942545b1e964a20279587fd7"
url = "https://github.com/JuliaWeb/OpenSSL.jl.git"

[depot.x86_64-linux.fetchgit.package-FilePathsBase]
name = "packages/FilePathsBase/9kSEl"
sha256 = "sha256-93CNyIMrnKKo8ZziZrDECb4SgpgGIfDF3eQLd8RLcg0="
rev = "e27c4ebe80e8699540f2d6c805cc12203b614f12"
url = "https://github.com/rofinn/FilePathsBase.jl.git"

[depot.x86_64-linux.fetchgit.package-FilePaths]
name = "packages/FilePaths/ULnpu"
sha256 = "sha256-aEvz0mvYwRGv+m7OFcZmbdhC6rtVm3OAjcD/blTq2KM="
rev = "919d9412dbf53a2e6fe74af62a73ceed0bce0629"
url = "https://github.com/rofinn/FilePaths.jl.git"

[depot.x86_64-linux.fetchgit.package-MbedTLS]
name = "packages/MbedTLS/lqmet"
sha256 = "sha256-X0cj/771qRxyVLloNLlhtrQkKKcVWlQxmqxSGVMYCII="
rev = "03a9b9718f5682ecb107ac9f7308991db4ce395b"
url = "https://github.com/JuliaLang/MbedTLS.jl.git"

[depot.x86_64-linux.fetchgit.package-DataValueInterfaces]
name = "packages/DataValueInterfaces/0j6Kp"
sha256 = "sha256-6FE9U6PRIY16wTNkW1kXlLDAT0eznWe6NSVJebCRXDw="
rev = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
url = "https://github.com/queryverse/DataValueInterfaces.jl.git"

[depot.x86_64-linux.fetchgit.package-CSTParser]
name = "packages/CSTParser/VcYj6"
sha256 = "sha256-8wxZ/b90hDZFQZTmdC+WhKFgI1WnuB7hoGRj8c1WfvA="
rev = "3ddd48d200eb8ddf9cb3e0189fc059fd49b97c1f"
url = "https://github.com/julia-vscode/CSTParser.jl.git"

[depot.x86_64-linux.fetchgit.package-Compat]
name = "packages/Compat/pIdfE"
sha256 = "sha256-rk/LzUu9MQXH9PgUhe1u/XB0b0ca93vNFK8qH1XQ0YE="
rev = "3ca828fe1b75fa84b021a7860bd039eaea84d2f2"
url = "https://github.com/JuliaLang/Compat.jl.git"

[depot.x86_64-linux.fetchgit.package-libsodium_jll]
name = "packages/libsodium_jll/GVKUC"
sha256 = "sha256-GaOXRXN82XxaL8rdzJAYMDtoH0S8e8QSQJdf0CZ5fZU="
rev = "848ab3d00fe39d6fbc2a8641048f8f272af1c51e"
url = "https://github.com/JuliaBinaryWrappers/libsodium_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-HTTP]
name = "packages/HTTP/a7H3J"
sha256 = "sha256-E9Lg/6D76IC8OKx+369QOcSnrC9OlT7viUVX+R1hrKI="
rev = "a97d47758e933cd5fe5ea181d178936a9fc60427"
url = "https://github.com/JuliaWeb/HTTP.jl.git"

[depot.x86_64-linux.fetchgit.package-Requires]
name = "packages/Requires/Z8rfN"
sha256 = "sha256-1Q47dgeivDgWcXvqby+oyAGg+YrEubYoAAWrE9zRuD4="
rev = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7"
url = "https://github.com/JuliaPackaging/Requires.jl.git"

[depot.x86_64-linux.fetchgit.package-LoggingExtras]
name = "packages/LoggingExtras/zT9ZU"
sha256 = "sha256-dh6B2gKpHH+26SMCK56yRq9GC6HDs7fCW8ILwgj8l/Q="
rev = "5d4d2d9904227b8bd66386c1138cf4d5ffa826bf"
url = "https://github.com/JuliaLogging/LoggingExtras.jl.git"

[depot.x86_64-linux.fetchgit.package-TableTraits]
name = "packages/TableTraits/o8VMV"
sha256 = "sha256-hKuGrmcOTiyoV8QyOUt1K7otbC0oKSwckqZyMIxYWiM="
rev = "c06b2f539df1c6efa794486abfb6ed2022561a39"
url = "https://github.com/queryverse/TableTraits.jl.git"

[depot.x86_64-linux.fetchgit.package-TestEnv]
name = "packages/TestEnv/bgEnl"
sha256 = "sha256-P7QekG/fn5KMuR+qJiDF215i5wTFR35QBiSHDtwmRwM="
rev = "974819eadfa8ac2e46b86e065917033252d3e92a"
url = "https://github.com/JuliaTesting/TestEnv.jl.git"

[depot.x86_64-linux.fetchgit.package-PackageCompiler]
name = "packages/PackageCompiler/DKijm"
sha256 = "sha256-gB+ff5DslQbjqIdBht1dXhz+YpVelXAy6OjE0IMjKs0="
rev = "f31ea705915b4e16e8104727ebd99e0c3993478d"
url = "https://github.com/JuliaLang/PackageCompiler.jl.git"

[depot.x86_64-linux.fetchgit.package-CodecZlib]
name = "packages/CodecZlib/ruMLE"
sha256 = "sha256-BL6c/f/6bbbn6e3qBOWwO3+vxwv7G9P/IpNP6u0ApnY="
rev = "ded953804d019afa9a3f98981d99b33e3db7b6da"
url = "https://github.com/JuliaIO/CodecZlib.jl.git"

[depot.x86_64-linux.fetchgit.package-Comonicon]
name = "packages/Comonicon/1NWD0"
sha256 = "sha256-RJIfJzJUbLXcHZ9hHUTV/nk91j2+tKc8uTX+np8k60U="
rev = "a414f42985134c5e9d59e1c4a63d7b16cd05fd15"
url = "https://github.com/comonicon/Comonicon.jl.git"

[depot.x86_64-linux.fetchgit.package-Git]
name = "packages/Git/EnxqL"
sha256 = "sha256-BqIhF5JJjruCf6jsW5YGKG1RG7FxNn3/X3sxYMb79i8="
rev = "d7bffc3fe097e9589145493c08c41297b457e5d0"
url = "https://github.com/JuliaVersionControl/Git.jl.git"

[depot.x86_64-linux.fetchgit.package-Libiconv_jll]
name = "packages/Libiconv_jll/tGWLj"
sha256 = "sha256-q0+kpW58lKLih0e2I7IVeb/Um+O3LmiaqgSHQOWhPDM="
rev = "42b62845d70a619f063a7da093d995ec8e15e778"
url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-Expat_jll]
name = "packages/Expat_jll/34w3j"
sha256 = "sha256-76MUkP7Yx5UrJpBeauMVJ0TYCdhYJiGyF4xWei2ZBxw="
rev = "bad72f730e9e91c08d9427d5e8db95478a3c323d"
url = "https://github.com/JuliaBinaryWrappers/Expat_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-JSON]
name = "packages/JSON/NeJ9k"
sha256 = "sha256-n2oLLNDn7qsRytMKXKUB653A14Yat+GiK9DgrkVBV9A="
rev = "3c837543ddb02250ef42f4738347454f95079d4e"
url = "https://github.com/JuliaIO/JSON.jl.git"

[depot.x86_64-linux.fetchgit.package-Glob]
name = "packages/Glob/GOSfX"
sha256 = "sha256-4EIDbc2mr4uhJtHjd802spC4wt914Az1ucUHswggipg="
rev = "4df9f7e06108728ebf00a0a11edee4b29a482bb2"
url = "https://github.com/vtjnash/Glob.jl.git"

[depot.x86_64-linux.fetchgit.package-SimpleBufferStream]
name = "packages/SimpleBufferStream/N1BA4"
sha256 = "sha256-oiV4k4jh+sJLWgbHoO0RWnpPVXHIlENIarRfEnBdqhw="
rev = "874e8867b33a00e784c8a7e4b60afe9e037b74e1"
url = "https://github.com/staticfloat/SimpleBufferStream.jl.git"

[depot.x86_64-linux.fetchgit.package-GitHub]
name = "packages/GitHub/O5XRk"
sha256 = "sha256-3DZbitcgsldBj/TrtJSMrvmZ15WXZ4GyidPdtUSIIco="
rev = "f1d3170f588c7610b568c9a97971915100dd51e8"
url = "https://github.com/JuliaWeb/GitHub.jl.git"

[depot.x86_64-linux.fetchgit.package-MacroTools]
name = "packages/MacroTools/qijNY"
sha256 = "sha256-qOuK1Ac2jb1yH6g/5kLuHTENnx8rvp9Cz+VLjKH5Zog="
rev = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
url = "https://github.com/FluxML/MacroTools.jl.git"

[depot.x86_64-linux.fetchgit.package-CommonMark]
name = "packages/CommonMark/qXeHg"
sha256 = "sha256-lWXwM+BaPWCQ7woHwyhV2bmV56F0FnKgfIQbUKw6ejI="
rev = "4cd7063c9bdebdbd55ede1af70f3c2f48fab4215"
url = "https://github.com/MichaelHatherly/CommonMark.jl.git"

[depot.x86_64-linux.fetchgit.package-Configurations]
name = "packages/Configurations/uH65h"
sha256 = "sha256-QboAqmZ1uUBwYjnKqASbDWHVUZC4CDWJ0o+nuUJ0mwE="
rev = "62a7c76dbad02fdfdaa53608104edf760938c4ca"
url = "https://github.com/Roger-luo/Configurations.jl.git"

[depot.x86_64-linux.fetchgit.package-TranscodingStreams]
name = "packages/TranscodingStreams/DYpJd"
sha256 = "sha256-hdHVTW2azsr2/zNV0B2XX5pdsQSD7YKOUa1tBm3R3i0="
rev = "8a75929dcd3c38611db2f8d08546decb514fcadf"
url = "https://github.com/JuliaIO/TranscodingStreams.jl.git"

[depot.x86_64-linux.fetchgit.package-JuliaFormatter]
name = "packages/JuliaFormatter/1SXYC"
sha256 = "sha256-OuJLtkLfdvS7DOlHwIK9iLMqQEYvRcr34Hhd2vdng34="
rev = "c4d23aa2863b1eba7f1756682055f72b24e183fd"
url = "https://github.com/domluna/JuliaFormatter.jl.git"

[depot.x86_64-linux.fetchgit.package-IteratorInterfaceExtensions]
name = "packages/IteratorInterfaceExtensions/NZdaj"
sha256 = "sha256-Cah708wvvD0Vxm63YZK1k7399B3rfONfckhJ2IJXl+o="
rev = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
url = "https://github.com/queryverse/IteratorInterfaceExtensions.jl.git"

[depot.x86_64-linux.fetchgit.package-Git_jll]
name = "packages/Git_jll/G4IMQ"
sha256 = "sha256-rEjJehQYEKInDVQMWp4GpE//T6wqsOy4L6rRpiWgdqc="
rev = "6e93d42b97978709e9c941fa43d0f01701f0d290"
url = "https://github.com/JuliaBinaryWrappers/Git_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-Gettext_jll]
name = "packages/Gettext_jll/5wIPp"
sha256 = "sha256-rvbsJ0HAiGvY/CIWn0bLqEPqsqcf0PlekgaDkzafHD4="
rev = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
url = "https://github.com/JuliaBinaryWrappers/Gettext_jll.jl.git"

[depot.x86_64-linux.fetchgit.package-JLLWrappers]
name = "packages/JLLWrappers/QpMQW"
sha256 = "sha256-HCas3QrKJJu2CPtTfe6HLCdajP5j84fxqvXmw6BJGHk="
rev = "abc9885a7ca2052a736a600f7fa66209f96506e1"
url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"

[depot.x86_64-linux.fetchgit.package-Tokenize]
name = "packages/Tokenize/bZ0tu"
sha256 = "sha256-cVxgoO4ACSUDPHX7g9Xr7I12P7SOGuH/VnGDpqzxbdA="
rev = "2b3af135d85d7e70b863540160208fa612e736b9"
url = "https://github.com/JuliaLang/Tokenize.jl.git"

[depot.x86_64-linux.fetchgit.package-ExproniconLite]
name = "packages/ExproniconLite/gn6gq"
sha256 = "sha256-lVMIs6wHhmEbp2RJhZZvLIWELKpitLHwB7QcdyZRyHE="
rev = "09dcb4512e103b2b8ad45aa35199633797654f47"
url = "https://github.com/Roger-luo/ExproniconLite.jl.git"

[depot.x86_64-linux.fetchgit.package-Ion]
name = "packages/Ion/N9mIF"
sha256 = "sha256-lCZSbYwfnLwzpHZJmG0KnoeN+5edZ2J69c85DfotIx0="
rev = "533d03a94b7034cdd415e9119de3b6c795db8b28"
url = "https://github.com/Roger-luo/Ion.jl"

[depot.x86_64-linux.fetchgit.package-LazyModules]
name = "packages/LazyModules/d9Be6"
sha256 = "sha256-89JTwTcprfPTi8VP/bF1KNUHXT15OJnUvGgMXrgCv4c="
rev = "a560dd966b386ac9ae60bdd3a3d3a326062d3c3e"
url = "https://github.com/johnnychen94/LazyModules.jl.git"

[depot.x86_64-linux.fetchgit.package-Reexport]
name = "packages/Reexport/OxbHO"
sha256 = "sha256-jle1YBDjUkczbAjSbp49wmgo9ucVVV5YacwG4AwuzkY="
rev = "45e428421666073eab6f2da5c9d310d99bb12f9b"
url = "https://github.com/simonster/Reexport.jl.git"

[depot.x86_64-linux.fetchgit.package-Scratch]
name = "packages/Scratch/u24Rl"
sha256 = "sha256-V717glkDqCFnUsj183Q1Ntufd3m2XzP18bvgqTWu7Wg="
rev = "f94f779c94e58bf9ea243e77a37e16d9de9126bd"
url = "https://github.com/JuliaPackaging/Scratch.jl.git"

[depot.x86_64-linux.fetchgit.package-IniFile]
name = "packages/IniFile/LzI2G"
sha256 = "sha256-7uQSdBYwRvH3/4aKXEE6U+AEMQnPmEGgl6sZt+U6vu4="
rev = "f550e6e32074c939295eb5ea6de31849ac2c9625"
url = "https://github.com/JuliaIO/IniFile.jl.git"

[depot.x86_64-linux.fetchgit.package-DataStructures]
name = "packages/DataStructures/59MD0"
sha256 = "sha256-D7O8UamRre+kEtHvnqDMnJwdsmXfn5OzBSil0Qh7ecY="
rev = "d1fff3a548102f48987a52a2e0d114fa97d730f0"
url = "https://github.com/JuliaCollections/DataStructures.jl.git"
